name: DevOps Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: 1 Checkout Code
      uses: actions/checkout@v4

    - name: 2 Build Step
      run: |
        echo "Starting Build..."
        echo "Build Successful"

    - name: 3 Build Report
      run: |
        echo "========== BUILD REPORT =========="
        echo "Project: DevOps Demo"
        echo "Status: BUILD SUCCESS"
        echo "Time: $(date)"
        echo "=================================="

    - name: 4 Deploy Step
      run: |
        echo "Starting Deployment..."
        echo "Deploy Successful"

    - name: 5 Deploy Report
      run: |
        echo "========== DEPLOY REPORT =========="
        echo "Project: DevOps Demo"
        echo "Status: DEPLOY SUCCESS"
        echo "Time: $(date)"
        echo "=================================="
